In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [39]:
df=pd.read_csv('/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [40]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [42]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [43]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [44]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [45]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [46]:
df =pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [48]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [49]:
df['Geography_Germany'] = df['Geography_Germany'].astype(int)
df['Geography_Spain'] = df['Geography_Spain'].astype(int)
df['Gender_Male'] = df['Gender_Male'].astype(int)

In [50]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [51]:
X=df.drop(columns=['Exited'])
y=df['Exited']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [52]:
X_train.shape

(8000, 11)

In [67]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [68]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [69]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [152]:
model =Sequential()

model.add(Dense(20,activation='relu',input_dim=11))
model.add(Dense(10,activation='relu'))
# model.add(Dense(8,activation='ReLU'))
# model.add(Dense(7,activation='ReLU'))
# model.add(Dense(6,activation='ReLU'))
# model.add(Dense(5,activation='ReLU'))
# model.add(Dense(4,activation='ReLU'))
# model.add(Dense(3,activation='ReLU'))
# model.add(Dense(2,activation='ReLU'))
model.add(Dense(1,activation='relu'))

In [153]:
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_59 (Dense)            (None, 20)                240

 dense_60 (Dense)            (None, 10)                210

 dense_61 (Dense)            (None, 1)                 11

=================================================================
Total params: 461
Trainable params: 461
Non-trainable params: 0
_________________________________________________________________

In [154]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [155]:
model.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
250/250 [==============================] - 1s 2ms/step - loss: 3.0622
Epoch 2/50
250/250 [==============================] - 0s 2ms/step - loss: 1.5767
Epoch 3/50
250/250 [==============================] - 0s 2ms/step - loss: 0.5719
Epoch 4/50
250/250 [==============================] - 0s 2ms/step - loss: 0.5159
Epoch 5/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4958
Epoch 6/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4802
Epoch 7/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4664
Epoch 8/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4660
Epoch 9/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4592
Epoch 10/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4489
Epoch 11/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4479
Epoch 12/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4263
Epoch 13/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4213
Epoch 14/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4152
Epoch 15/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4088
Epoch 16/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4033
Epoch 17/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4002
Epoch 18/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3932
Epoch 19/50
250/250 [==============================] - 1s 2ms/step - loss: 0.3907
Epoch 20/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3852
Epoch 21/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3723
Epoch 22/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3730
Epoch 23/50
250/250 [==============================] - 1s 2ms/step - loss: 0.3650
Epoch 24/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3713
Epoch 25/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3743
Epoch 26/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3989
Epoch 27/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3654
Epoch 28/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3602
Epoch 29/50
250/250 [==============================] - 1s 2ms/step - loss: 0.3549
Epoch 30/50
250/250 [==============================] - 1s 2ms/step - loss: 0.3574
Epoch 31/50
250/250 [==============================] - 1s 2ms/step - loss: 0.3565
Epoch 32/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3819
Epoch 33/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3595
Epoch 34/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3506
Epoch 35/50
250/250 [==============================] - 1s 2ms/step - loss: 0.3502
Epoch 36/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3484
Epoch 37/50
250/250 [==============================] - 1s 2ms/step - loss: 0.3464
Epoch 38/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3557
Epoch 39/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3486
Epoch 40/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3471
Epoch 41/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3441
Epoch 42/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3427
Epoch 43/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3781
Epoch 44/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3463
Epoch 45/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3450
Epoch 46/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3432
Epoch 47/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3401
Epoch 48/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3389
Epoch 49/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3379
Epoch 50/50
250/250 [==============================] - 0s 2ms/step - loss: 0.3436

In [157]:
model.layers[1].get_weights()

[array([[-3.34944606e-01,  1.15514793e-01, -1.40560701e-01,
          3.06210462e-02, -4.65316683e-01, -1.30332440e-01,
         -1.70712434e-02, -4.04687971e-01,  2.13776335e-01,
          2.20463946e-01],
        [-3.83523375e-01, -2.05424115e-01, -3.19751352e-02,
          1.64833680e-01, -5.07103682e-01, -4.74850595e-01,
          1.90329120e-01, -7.03754723e-02, -1.37986168e-01,
         -6.43522069e-02],
        [-3.02177966e-01,  6.81399032e-02, -1.63144320e-01,
         -2.18552202e-01, -6.98510408e-01,  4.50787805e-02,
         -2.70378202e-01,  3.39788646e-02, -5.66819131e-01,
          2.56608725e-01],
        [ 1.38521016e-01, -1.69467196e-01,  3.10632944e-01,
         -1.00221317e-02, -3.48543674e-01, -2.51617640e-01,
          2.28857379e-02,  1.86405033e-01,  3.83706868e-01,
          2.36470178e-02],
        [ 2.84523033e-02, -1.21801235e-01, -3.60318661e-01,
         -3.41843963e-01, -1.41442880e-01, -3.40249360e-01,
         -5.77156618e-02, -4.30856019e-01, -4.25850935e-02,
          1.65525541e-01],
        [ 2.59945571e-01,  4.10741925e-01,  6.96826100e-01,
         -2.07961604e-01,  3.87693882e-01, -6.81312203e-01,
          2.02853456e-01, -1.36660980e-02,  6.66915113e-03,
          6.39044773e-03],
        [ 3.45588952e-01, -9.98141244e-03,  3.43719065e-01,
         -1.47705659e-01, -5.62569732e-03,  3.01798694e-02,
         -1.40369669e-01, -4.86538738e-01,  1.41172245e-01,
         -2.02577204e-01],
        [-4.70528424e-01, -2.69831955e-01,  5.08670390e-01,
          9.04538184e-02, -2.23505050e-01,  3.66647840e-02,
         -9.03790966e-02,  5.17389119e-01, -3.71965855e-01,
          5.49468517e-01],
        [ 2.29131699e-01,  2.77905434e-01,  1.99077517e-01,
          2.50210136e-01, -2.87596792e-01, -1.60945192e-01,
         -1.81408778e-01, -4.12400663e-01, -4.44998741e-02,
          4.79495414e-02],
        [ 2.65796810e-01,  3.59413445e-01, -4.80988026e-01,
          4.05616999e-01, -5.60647964e-01,  3.36309016e-01,
          1.90722704e-01,  1.34950370e-01, -4.77225557e-02,
          8.39296877e-02],
        [ 1.25403315e-01, -4.02599834e-02, -1.25738785e-01,
          2.21949384e-01,  2.31248021e-01,  4.52918559e-02,
         -5.09781659e-01, -4.27833527e-01, -2.23536432e-01,
         -3.55568372e-05],
        [ 2.99017996e-01,  2.00062647e-01, -4.39425819e-02,
         -3.22579801e-01,  3.37798715e-01,  1.28892332e-01,
          2.72656769e-01,  4.08166558e-01, -1.85679346e-01,
          1.48429275e-01],
        [-4.35076714e-01, -1.40801920e-02,  7.59460554e-02,
         -9.59754884e-02, -3.38558815e-02,  4.55824956e-02,
         -7.72924900e-01,  3.41400743e-01, -7.66093373e-01,
         -5.53282537e-02],
        [-1.80754408e-01,  1.73379764e-01,  5.47984838e-01,
         -1.55387968e-01, -2.72969693e-01, -2.60667056e-01,
          1.56516925e-01, -4.33457009e-02,  3.00743043e-01,
          4.51570362e-01],
        [ 3.18906486e-01, -2.06826121e-01,  2.25397632e-01,
         -5.55765852e-02, -4.47928607e-01,  2.23451585e-01,
          3.03900868e-01, -2.72201113e-02,  3.43797833e-01,
          2.63859741e-02],
        [-1.37780428e-01,  5.02978861e-01, -1.62094370e-01,
          3.42677623e-01, -1.43071041e-01,  2.83961296e-01,
         -1.86596643e-02,  1.33964136e-01, -2.79205106e-02,
          1.47381008e-01],
        [-1.05165243e-01,  1.86386928e-01,  5.31009734e-01,
          2.82569900e-02,  1.48502216e-01, -4.27820444e-01,
         -1.89128667e-02,  1.37097258e-02, -1.99844778e-01,
          4.66309249e-01],
        [ 2.20482409e-01, -4.80126925e-02, -6.77743331e-02,
         -7.70247579e-02,  1.35181487e-01, -2.74757892e-01,
          9.01298150e-02, -1.75796505e-02, -1.99628279e-01,
         -4.22834128e-01],
        [ 3.49766523e-01,  1.37263849e-01,  4.80480045e-01,
          5.39199859e-02, -4.21921611e-01, -4.08798456e-01,
         -1.54052544e-02, -1.28200874e-01,  3.07119370e-01,
          1.72661185e-01],
        [-2.57945836e-01, -1.54893681e-01,  3.30086023e-01,
         -5.73955067e-02,  1.37996376e-01, -2.87025511e-01,
          2.67932773e-01, -2.75482625e-01,  3.05738300e-01,
         -4.47203815e-01]], dtype=float32),
 array([-0.11840316,  0.02647222,  0.07308877, -0.14902769, -0.00300808,
        -0.10488824, -0.05401997, -0.03081743, -0.12653603, -0.02904702],
       dtype=float32)]

In [158]:
y_log=model.predict(X_test_scaled)

63/63 [==============================] - 0s 1ms/step

In [159]:
from sklearn.metrics import accuracy_score

In [161]:
l=[]
for _ in range(100):
    
    y_pred=np.where(y_log>(_/10),1,0)

    l.append(accuracy_score(y_test,y_pred))

print(l.index(min(l))/10)
print(l)

0.0
[0.365, 0.594, 0.7475, 0.8295, 0.859, 0.8595, 0.854, 0.847, 0.8385, 0.826, 0.8145, 0.808, 0.8055, 0.8025, 0.8005, 0.7985, 0.7975, 0.797, 0.7965, 0.7945, 0.7945, 0.794, 0.7935, 0.793, 0.793, 0.793, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925, 0.7925]

In [151]:
accuracy_score(y_test,y_pred)

0.808